services:
  - type: web
    name: grant-db-api
    env: python
    runtime: python-3.12
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        sync: false
